# Generated by Django 4.0.1 on 2022-02-18 11:24

import MyBody.catalog.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_likearticle_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.TextField(validators=[django.core.validators.MinValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(upload_to='media/articles', validators=[MyBody.catalog.validators.MaxSizeImageValidator(5)]),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=20, validators=[django.core.validators.MinValueValidator(5)]),
        ),
    ]
