# Generated by Django 4.0.1 on 2022-03-02 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_commentmodel_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmodel',
            name='article',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='catalog.article'),
        ),
    ]
