# Generated by Django 4.0.1 on 2022-04-20 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Navigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=20, null=True)),
                ('left_side', models.BooleanField(default=True)),
                ('url_name', models.CharField(choices=[('home', 'home'), ('login', 'login'), ('register', 'register'), ('logout', 'logout'), ('catalog', 'catalog'), ('search catalog', 'search catalog')], max_length=14)),
                ('my_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['my_order'],
            },
        ),
    ]
