# Generated by Django 4.0.1 on 2022-04-20 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigation',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
