# Generated by Django 4.0.1 on 2022-04-20 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0003_alter_navigation_url_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigation',
            name='fa_icon',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
