# Generated by Django 4.0.1 on 2022-02-16 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_description_profile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.TextField(blank=True, default='Not selected', max_length=100, null=True),
        ),
    ]
